gui:
  nerdFontsVersion: "3"
  scrollHeight: 4
  showListFooter: false
  showRandomTip: false
  showCommandLog: false
  showPanelJumps: false
  theme:
    inactiveBorderColor:
      - blue
    selectedLineBgColor:
      - "#313244"
os:
  editPreset: "nvim"
